# Generated by Django 2.2.6 on 2020-05-16 07:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_auto_20200516_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 7, 57, 52, 17817, tzinfo=utc)),
        ),
    ]
