# Generated by Django 2.2.6 on 2020-05-27 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_auto_20200526_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 27, 19, 38, 37, 535418)),
        ),
    ]
