# Generated by Django 2.2.6 on 2020-05-28 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_auto_20200527_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 28, 15, 20, 11, 76481)),
        ),
    ]
